import {
  Squares2X2Icon,
  SparklesIcon,
  GlobeAltIcon,
  BuildingLibraryIcon,
  GiftIcon,
  HeartIcon,
  QuestionMarkCircleIcon,
  DocumentDuplicateIcon,
  CubeIcon,
  UserGroupIcon,
  CreditCardIcon,
  ClipboardDocumentListIcon,
  DocumentTextIcon,
  BanknotesIcon,
  TableCellsIcon,
  BellAlertIcon,
  BeakerIcon,
  BriefcaseIcon,
  CalendarIcon,
  ChatBubbleLeftRightIcon,
  CurrencyDollarIcon,
  ArrowDownTrayIcon,
  BanknotesIcon as CoinsIcon,
  ShieldCheckIcon,
} from '@heroicons/react/24/outline';

export const ADMIN_NAV_ITEMS = [
  { key: 'dashboard', label: 'Dashboard', icon: Squares2X2Icon, mode: 'internal', path: '/admin/dashboard' },
  { key: 'requests', label: 'Requests', icon: ShieldCheckIcon, mode: 'route', path: '/admin/requests' },
  { key: 'interest', label: 'Interest', icon: SparklesIcon, mode: 'internal', path: '/admin/dashboard' },
  { key: 'language', label: 'Language', icon: GlobeAltIcon, mode: 'internal', path: '/admin/dashboard' },
  { key: 'religion', label: 'Religion', icon: BuildingLibraryIcon, mode: 'internal', path: '/admin/dashboard' },
  { key: 'relation_goal', label: 'Relation Goal', icon: HeartIcon, mode: 'internal', path: '/admin/dashboard' },
  { key: 'gift', label: 'Gift Management', icon: GiftIcon, mode: 'route', path: '/admin/gift-management' },
  { key: 'faq', label: 'FAQ', icon: QuestionMarkCircleIcon, mode: 'internal', path: '/admin/dashboard' },
  { key: 'plan', label: 'Plan', icon: DocumentDuplicateIcon, mode: 'route', path: '/admin/plans' },
  { key: 'coinPackages', label: 'Coin Packages', icon: CurrencyDollarIcon, mode: 'route', path: '/admin/coin-packages' },
  { key: 'coins', label: 'Coins', icon: CoinsIcon, mode: 'route', path: '/admin/coins' },
  { key: 'package', label: 'Package', icon: CubeIcon, mode: 'internal', path: '/admin/dashboard' },
  { key: 'staff', label: 'Staff', icon: BriefcaseIcon, mode: 'coming' },
  { key: 'paymentList', label: 'Payment List', icon: CreditCardIcon, mode: 'route', path: '/admin/payments' },
  { key: 'fakeGenerator', label: 'Fake User Generator', icon: BeakerIcon, mode: 'internal', path: '/admin/dashboard' },
  { key: 'fakeUsers', label: 'Fake Users', icon: UserGroupIcon, mode: 'route', path: '/admin/fake-users' },
  { key: 'reportList', label: 'Report List', icon: ClipboardDocumentListIcon, mode: 'coming' },
  { key: 'pages', label: 'Page Content', icon: DocumentTextIcon, mode: 'route', path: '/admin/pages' },
  { key: 'payoutList', label: 'Payout List', icon: BanknotesIcon, mode: 'route', path: '/admin/payments' },
  { key: 'withdrawRequests', label: 'Withdraw Requests', icon: ArrowDownTrayIcon, mode: 'route', path: '/admin/withdrawals' },
  { key: 'userList', label: 'User List', icon: TableCellsIcon, mode: 'route', path: '/admin/users' },
  { key: 'events', label: 'Events', icon: CalendarIcon, mode: 'route', path: '/admin/events' },
  { key: 'forums', label: 'Forums', icon: ChatBubbleLeftRightIcon, mode: 'route', path: '/admin/forums' },
  { key: 'icebreakers', label: 'Ice-Breakers', icon: SparklesIcon, mode: 'route', path: '/admin/icebreakers' },
  { key: 'chats', label: 'Chats Monitoring', icon: ChatBubbleLeftRightIcon, mode: 'route', path: '/admin/chats' },
  { key: 'gifts', label: 'Gifts Monitoring', icon: GiftIcon, mode: 'route', path: '/admin/gifts' },
  { key: 'pushNotification', label: 'Push Notification', icon: BellAlertIcon, mode: 'route', path: '/admin/push-notifications' },
];
